version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: mediq-db
    environment:
      POSTGRES_DB: mediq_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - pgdata:/var/lib/postgresql/data

  ml-service:
    build: ./ml-service
    container_name: mediq-ml-service
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  backend:
    build: ./backend
    container_name: mediq-backend
    depends_on:
      - postgres
      - ml-service
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mediq_db

  frontend:
    build: ./frontend
    container_name: mediq-frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  pgdata:
