spring.datasource.url=jdbc:postgresql://localhost:5432/mediq_db
spring.datasource.username=postgres
spring.datasource.password=mediq123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080

# URL of the Python ML microservice
ml.service.base-url=http://localhost:8000
